// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"github.com/vattle/sqlboiler/types"
)

// GuestList is an object representing the database table.
type GuestList struct {
	ID   int        `boil:"id" json:"id" toml:"id" yaml:"id"`
	Data types.JSON `boil:"data" json:"data" toml:"data" yaml:"data"`

	R *guestListR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L guestListL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// guestListR is where relationships are stored.
type guestListR struct {
	GuestParties PartySlice
}

// guestListL is where Load methods for each relationship are stored.
type guestListL struct{}

var (
	guestListColumns               = []string{"id", "data"}
	guestListColumnsWithoutDefault = []string{"data"}
	guestListColumnsWithDefault    = []string{"id"}
	guestListPrimaryKeyColumns     = []string{"id"}
)

type (
	// GuestListSlice is an alias for a slice of pointers to GuestList.
	// This should generally be used opposed to []GuestList.
	GuestListSlice []*GuestList

	guestListQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	guestListType                 = reflect.TypeOf(&GuestList{})
	guestListMapping              = queries.MakeStructMapping(guestListType)
	guestListPrimaryKeyMapping, _ = queries.BindMapping(guestListType, guestListMapping, guestListPrimaryKeyColumns)
	guestListInsertCacheMut       sync.RWMutex
	guestListInsertCache          = make(map[string]insertCache)
	guestListUpdateCacheMut       sync.RWMutex
	guestListUpdateCache          = make(map[string]updateCache)
	guestListUpsertCacheMut       sync.RWMutex
	guestListUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single guestList record from the query, and panics on error.
func (q guestListQuery) OneP() *GuestList {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single guestList record from the query.
func (q guestListQuery) One() (*GuestList, error) {
	o := &GuestList{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for guest_list")
	}

	return o, nil
}

// AllP returns all GuestList records from the query, and panics on error.
func (q guestListQuery) AllP() GuestListSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all GuestList records from the query.
func (q guestListQuery) All() (GuestListSlice, error) {
	var o []*GuestList

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GuestList slice")
	}

	return o, nil
}

// CountP returns the count of all GuestList records in the query, and panics on error.
func (q guestListQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all GuestList records in the query.
func (q guestListQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count guest_list rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q guestListQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q guestListQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if guest_list exists")
	}

	return count > 0, nil
}

// GuestPartiesG retrieves all the party's party via guests_id column.
func (o *GuestList) GuestPartiesG(mods ...qm.QueryMod) partyQuery {
	return o.GuestParties(boil.GetDB(), mods...)
}

// GuestParties retrieves all the party's party with an executor via guests_id column.
func (o *GuestList) GuestParties(exec boil.Executor, mods ...qm.QueryMod) partyQuery {
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"a\".\"guests_id\"=?", o.ID),
	)

	query := Parties(exec, queryMods...)
	queries.SetFrom(query.Query, "\"party\" as \"a\"")
	return query
}

// LoadGuestParties allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (guestListL) LoadGuestParties(e boil.Executor, singular bool, maybeGuestList interface{}) error {
	var slice []*GuestList
	var object *GuestList

	count := 1
	if singular {
		object = maybeGuestList.(*GuestList)
	} else {
		slice = *maybeGuestList.(*[]*GuestList)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &guestListR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &guestListR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"party\" where \"guests_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load party")
	}
	defer results.Close()

	var resultSlice []*Party
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice party")
	}

	if singular {
		object.R.GuestParties = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.GuestsID {
				local.R.GuestParties = append(local.R.GuestParties, foreign)
				break
			}
		}
	}

	return nil
}

// AddGuestPartiesG adds the given related objects to the existing relationships
// of the guest_list, optionally inserting them as new records.
// Appends related to o.R.GuestParties.
// Sets related.R.Guest appropriately.
// Uses the global database handle.
func (o *GuestList) AddGuestPartiesG(insert bool, related ...*Party) error {
	return o.AddGuestParties(boil.GetDB(), insert, related...)
}

// AddGuestPartiesP adds the given related objects to the existing relationships
// of the guest_list, optionally inserting them as new records.
// Appends related to o.R.GuestParties.
// Sets related.R.Guest appropriately.
// Panics on error.
func (o *GuestList) AddGuestPartiesP(exec boil.Executor, insert bool, related ...*Party) {
	if err := o.AddGuestParties(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddGuestPartiesGP adds the given related objects to the existing relationships
// of the guest_list, optionally inserting them as new records.
// Appends related to o.R.GuestParties.
// Sets related.R.Guest appropriately.
// Uses the global database handle and panics on error.
func (o *GuestList) AddGuestPartiesGP(insert bool, related ...*Party) {
	if err := o.AddGuestParties(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddGuestParties adds the given related objects to the existing relationships
// of the guest_list, optionally inserting them as new records.
// Appends related to o.R.GuestParties.
// Sets related.R.Guest appropriately.
func (o *GuestList) AddGuestParties(exec boil.Executor, insert bool, related ...*Party) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.GuestsID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"party\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"guests_id"}),
				strmangle.WhereClause("\"", "\"", 2, partyPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.GuestsID = o.ID
		}
	}

	if o.R == nil {
		o.R = &guestListR{
			GuestParties: related,
		}
	} else {
		o.R.GuestParties = append(o.R.GuestParties, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &partyR{
				Guest: o,
			}
		} else {
			rel.R.Guest = o
		}
	}
	return nil
}

// GuestListsG retrieves all records.
func GuestListsG(mods ...qm.QueryMod) guestListQuery {
	return GuestLists(boil.GetDB(), mods...)
}

// GuestLists retrieves all the records using an executor.
func GuestLists(exec boil.Executor, mods ...qm.QueryMod) guestListQuery {
	mods = append(mods, qm.From("\"guest_list\""))
	return guestListQuery{NewQuery(exec, mods...)}
}

// FindGuestListG retrieves a single record by ID.
func FindGuestListG(id int, selectCols ...string) (*GuestList, error) {
	return FindGuestList(boil.GetDB(), id, selectCols...)
}

// FindGuestListGP retrieves a single record by ID, and panics on error.
func FindGuestListGP(id int, selectCols ...string) *GuestList {
	retobj, err := FindGuestList(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindGuestList retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGuestList(exec boil.Executor, id int, selectCols ...string) (*GuestList, error) {
	guestListObj := &GuestList{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"guest_list\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(guestListObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from guest_list")
	}

	return guestListObj, nil
}

// FindGuestListP retrieves a single record by ID with an executor, and panics on error.
func FindGuestListP(exec boil.Executor, id int, selectCols ...string) *GuestList {
	retobj, err := FindGuestList(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *GuestList) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *GuestList) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *GuestList) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *GuestList) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no guest_list provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(guestListColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	guestListInsertCacheMut.RLock()
	cache, cached := guestListInsertCache[key]
	guestListInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			guestListColumns,
			guestListColumnsWithDefault,
			guestListColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(guestListType, guestListMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(guestListType, guestListMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"guest_list\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"guest_list\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into guest_list")
	}

	if !cached {
		guestListInsertCacheMut.Lock()
		guestListInsertCache[key] = cache
		guestListInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single GuestList record. See Update for
// whitelist behavior description.
func (o *GuestList) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single GuestList record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *GuestList) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the GuestList, and panics on error.
// See Update for whitelist behavior description.
func (o *GuestList) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the GuestList.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *GuestList) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	guestListUpdateCacheMut.RLock()
	cache, cached := guestListUpdateCache[key]
	guestListUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			guestListColumns,
			guestListPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update guest_list, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"guest_list\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, guestListPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(guestListType, guestListMapping, append(wl, guestListPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update guest_list row")
	}

	if !cached {
		guestListUpdateCacheMut.Lock()
		guestListUpdateCache[key] = cache
		guestListUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q guestListQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q guestListQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for guest_list")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o GuestListSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o GuestListSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o GuestListSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GuestListSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), guestListPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"guest_list\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, guestListPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in guestList slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *GuestList) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *GuestList) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *GuestList) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *GuestList) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no guest_list provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(guestListColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	guestListUpsertCacheMut.RLock()
	cache, cached := guestListUpsertCache[key]
	guestListUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			guestListColumns,
			guestListColumnsWithDefault,
			guestListColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			guestListColumns,
			guestListPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert guest_list, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(guestListPrimaryKeyColumns))
			copy(conflict, guestListPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"guest_list\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(guestListType, guestListMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(guestListType, guestListMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert guest_list")
	}

	if !cached {
		guestListUpsertCacheMut.Lock()
		guestListUpsertCache[key] = cache
		guestListUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single GuestList record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *GuestList) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single GuestList record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *GuestList) DeleteG() error {
	if o == nil {
		return errors.New("models: no GuestList provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single GuestList record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *GuestList) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single GuestList record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GuestList) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no GuestList provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), guestListPrimaryKeyMapping)
	sql := "DELETE FROM \"guest_list\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from guest_list")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q guestListQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q guestListQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no guestListQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from guest_list")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o GuestListSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o GuestListSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no GuestList slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o GuestListSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GuestListSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no GuestList slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), guestListPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"guest_list\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, guestListPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from guestList slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *GuestList) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *GuestList) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *GuestList) ReloadG() error {
	if o == nil {
		return errors.New("models: no GuestList provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GuestList) Reload(exec boil.Executor) error {
	ret, err := FindGuestList(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *GuestListSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *GuestListSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GuestListSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty GuestListSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GuestListSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	guestLists := GuestListSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), guestListPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"guest_list\".* FROM \"guest_list\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, guestListPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&guestLists)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GuestListSlice")
	}

	*o = guestLists

	return nil
}

// GuestListExists checks if the GuestList row exists.
func GuestListExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"guest_list\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if guest_list exists")
	}

	return exists, nil
}

// GuestListExistsG checks if the GuestList row exists.
func GuestListExistsG(id int) (bool, error) {
	return GuestListExists(boil.GetDB(), id)
}

// GuestListExistsGP checks if the GuestList row exists. Panics on error.
func GuestListExistsGP(id int) bool {
	e, err := GuestListExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// GuestListExistsP checks if the GuestList row exists. Panics on error.
func GuestListExistsP(exec boil.Executor, id int) bool {
	e, err := GuestListExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
